AWS_REGION = ENV['AWS_REGION'] || "us-east-1"
AWS_AMI = ENV['AWS_AMI'] || "ami-1b135e72"
AWS_TYPE = ENV['AWS_TYPE'] || "t1.micro"

Vagrant.configure("2") do |config|
    config.vm.box = "dummy"

    config.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV["AWS_ACCESS_KEY_ID"]
        aws.secret_access_key = ENV["AWS_SECRET_ACCESS_KEY"]
        aws.keypair_name = ENV["AWS_KEYPAIR_NAME"]
        override.ssh.private_key_path = ENV["AWS_SSH_PRIVKEY"]
        aws.instance_type = AWS_TYPE
        aws.region = AWS_REGION
        aws.ami = AWS_AMI
        aws.security_groups = ["salt-master"]
        aws.tags = {
            'Name' => 'Salt Master',
        }
        override.ssh.username = "ubuntu"
    end
end
